### ISSUE TITLE
I have problem executing the program. 

### ISSUE THREAD

**Issue by Fusheinijb** [tolgatasci/Traffic-Generator-with-Docker-and-Tor#3]
┌──(spider㉿kali)-[~/Documents/Clone/Traffic-Generator-with-Docker-and-Tor]
└─$ sudo docker run --name test6 traffic -loop 5 -u https://www.google.com -l 5 -d True -w 5
Nov 28 17:11:31.061 [notice] Tor 0.4.2.7 running on Linux with Libevent 2.1.11-stable, OpenSSL 1.1.1f, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.4.4.
Nov 28 17:11:31.094 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Nov 28 17:11:31.095 [notice] Read configuration file "/etc/tor/torrc".
Nov 28 17:11:31.100 [warn] You have a ControlPort set to accept connections from a non-local address.  This means that programs not running on your computer can reconfigure your Tor.  That's pretty bad, since the controller protocol isn't encrypted!  Maybe you should just listen on 127.0.0.1 and use a tool like stunnel or ssh to encrypt remote connections to your control port.
Nov 28 17:11:31.101 [warn] You specified a public address '0.0.0.0:9050' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
Nov 28 17:11:31.101 [warn] You have a ControlPort set to accept connections from a non-local address.  This means that programs not running on your computer can reconfigure your Tor.  That's pretty bad, since the controller protocol isn't encrypted!  Maybe you should just listen on 127.0.0.1 and use a tool like stunnel or ssh to encrypt remote connections to your control port.
Nov 28 17:11:31.101 [notice] Opening Socks listener on 0.0.0.0:9050
Nov 28 17:11:31.101 [notice] Opened Socks listener on 0.0.0.0:9050
Nov 28 17:11:31.101 [notice] Opening Control listener on 0.0.0.0:9051
Nov 28 17:11:31.101 [notice] Opened Control listener on 0.0.0.0:9051
https://www.google.com
Traceback (most recent call last):
  File "hit.py", line 101, in <module>
    setup()
  File "hit.py", line 42, in setup
    driver = webdriver.Chrome(executable_path="/chromedriver/chromedriver",options=chrome_options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 107.0.5304.121 with binary path /usr/bin/google-chrome

https://www.google.com
Traceback (most recent call last):
  File "hit.py", line 101, in <module>
    setup()
  File "hit.py", line 42, in setup
    driver = webdriver.Chrome(executable_path="/chromedriver/chromedriver",options=chrome_options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 107.0.5304.121 with binary path /usr/bin/google-chrome

https://www.google.com
Traceback (most recent call last):
  File "hit.py", line 101, in <module>
    setup()
  File "hit.py", line 42, in setup
    driver = webdriver.Chrome(executable_path="/chromedriver/chromedriver",options=chrome_options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 107.0.5304.121 with binary path /usr/bin/google-chrome

https://www.google.com
Traceback (most recent call last):
  File "hit.py", line 101, in <module>
    setup()
  File "hit.py", line 42, in setup
    driver = webdriver.Chrome(executable_path="/chromedriver/chromedriver",options=chrome_options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 107.0.5304.121 with binary path /usr/bin/google-chrome

https://www.google.com
Traceback (most recent call last):
  File "hit.py", line 101, in <module>
    setup()
  File "hit.py", line 42, in setup
    driver = webdriver.Chrome(executable_path="/chromedriver/chromedriver",options=chrome_options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 107.0.5304.121 with binary path /usr/bin/google-chrome

https://www.google.com
Traceback (most recent call last):
  File "hit.py", line 101, in <module>
    setup()
  File "hit.py", line 42, in setup
    driver = webdriver.Chrome(executable_path="/chromedriver/chromedriver",options=chrome_options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 107.0.5304.121 with binary path /usr/bin/google-chrome

**Comment by tolgatasci** [comment]
This version of ChromeDriver only supports Chrome version 102
Current browser version is 107.0.5304.121 with binary path /usr/bin/google-chrome

chrome version and driver version not support we have to upgrade.
I will look in my free time

**Comment by Fusheinijb** [comment]
Thanks you so much for replying me. I have been try about three days now to solve the problem but haven't yet solve it. All the the solutions I have try so far is giving me the same error.

I hope and count on you to help me solve the problem. Thank you.

**Comment by Fusheinijb** [comment]
Thank you so much for replying me. I have been try about three days now to solve the problem but haven't yet solve it. All the the solutions I have try so far is giving me the same error.

I hope and count on you to help me solve the problem. Thank you.
